### ISSUE TITLE
Minor Typo in StopInputHandlerDirective

### ISSUE THREAD

**Issue by terrenjpeterson** [alexa/skill-sample-nodejs-buttons-hellobuttons#5]
In the buttonStopIntpuHandlerDirective class there is a spelling mistake.  It's consistently wrong so it works, but if you accidentally spell it correctly (i.e. spell it buttonStopInputHandlerDirective) it then won't work.

**Comment by mdinescu** [comment]
Thanks for catching and reporting this. The typo was corrected.
