### ISSUE TITLE
Example does not execute - `There was a problem with the requested skill's response`

### ISSUE THREAD

**Issue by error454** [alexa/skill-sample-nodejs-buttons-hellobuttons#7]
I've followed these instructions twice from start to finish and get the same result.

Running in both the dev console and on an actual device, alexa responds with `There was a problem with the requested skill's response`.

Looking at cloudwatch, I see that `LaunchRequestHandler` is fired to handle the request but then I immediately see an `===EVENT===` log with error:

```javascript
"request": {
        "type": "SessionEndedRequest",
        "requestId": "amzn1.echo-api.request.820de902-c11e-4355-a864-7a3982bac373",
        "timestamp": "2018-09-08T20:21:24Z",
        "locale": "en-US",
        "reason": "ERROR",
        "error": {
            "type": "INVALID_RESPONSE",
            "message": "SpeechletResponse was null"
        }
    }
```

And then 
`2018-09-08T20:21:24.885Z	c22715f8-b3a4-11e8-9749-b9ff6efbcc42	Session ended with reason: ERROR`

I've tried pairing the LaunchRequestHandler down to:
```javascript
return handlerInput.responseBuilder
        .speak("Test").getResponse();
```
But things still fail with the same footprint.

As the aws stuff changes rapidly, are there any obvious changes in the last 2 months that could explain this?

**Comment by mdinescu** [comment]
Hi Zach,

Please try to change the version of you Lambda NodeJS runtime to 8.10.  It seems like you're running an old version of NodeJS which is incompatible with the Alexa SDK for Node JS v2.

Please update this issue and let me know if that worked or not.

--
Mike

**Comment by error454** [comment]
Thanks Mike! This was indeed the issue. I've submitted #8 to bring the documentation up to parity with the current Alexa dev console and NodeJS requirements.

**Comment by mdinescu** [comment]
Thanks Zach! I'll take a look and pull it in on Monday.
